-- affSpringer.m2
-- Affine Springer loci in the affine Grassmannian for GL_n.
--
-- Requires affGrSchubert.m2.

load "affGrSchubert.m2"

-- FUNCTIONS
--
-- (1) openNablaSpringer(n, lam, mu, e)
--     Returns (J, f) where:
--       J = ideal in A = ((ring I) / I)[y_(i,j,k), pi_1, ..., pi_(e-1)],
--           cutting out the closed locus where the connection
--           nabla = N(u) + (u-pi_1)...(u-pi_(e-1)) * u * d/du
--           preserves the tautological lattice on the affine open chart of
--           Gr_{<= lam} around u^mu,
--       f = the tautological frame over A, obtained from the open
--           Schubert chart.
--
--     Here N(u) = sum_{k=1}^{lam_0-1} Y_k u^k with
--     Y_k = (y_(i,j,k))_(i,j).


-------------------------------------------------------------------------------
-- AUXILIARY FUNCTIONS
-------------------------------------------------------------------------------

-- adjugateMatrixGLn(M)
-- Returns the classical adjugate matrix of the square matrix M.
adjugateMatrixGLn = M -> (
    m := numrows M;
    n := numcols M;
    if m =!= n then error("adjugateMatrixGLn: matrix must be square");

    RM := ring M;
    if n == 1 then matrix{{1_RM}} else (
        allRows := toList(0..n-1);
        allCols := toList(0..n-1);
        matrix table(n, n, (i,j) -> (
            rowsKeep := select(allRows, r -> r != j);
            colsKeep := select(allCols, c -> c != i);
            (-1)^(i+j) * det submatrix(M, rowsKeep, colsKeep)
        ))
    )
);

-------------------------------------------------------------------------------
-- MAIN FUNCTION 1: openNablaSpringer
-------------------------------------------------------------------------------

openNablaSpringer = (n, lam, mu, e) -> (
    -- Validate exactly as in openSchubertGLn, together with e >= 1.
    if #lam != n then error("openNablaSpringer: lambda must have length n");
    if #mu != n then error("openNablaSpringer: mu must have length n");
    if not all(0..n-2, i -> lam#i >= lam#(i+1)) then
        error("openNablaSpringer: lambda must be weakly decreasing");
    if not all(0..n-2, i -> mu#i >= mu#(i+1)) then
        error("openNablaSpringer: mu must be weakly decreasing");
    if mu#(n-1) < 0 then
        error("openNablaSpringer: mu entries must be nonnegative");
    if sum mu != sum lam then
        error("openNablaSpringer: |mu| must equal |lambda|");
    scan(n-1, k -> (
        if sum take(mu, k+1) > sum take(lam, k+1) then
            error("openNablaSpringer: mu is not <= lambda in dominance order");
    ));
    if class e =!= ZZ or e < 1 then
        error("openNablaSpringer: e must be a positive integer");

    N := lam#0;
    nN := n * N;
    D := sum lam;
    d := nN - D;
    if d <= 0 or d >= nN then
        error("openNablaSpringer: degenerate case, d = " | toString d);

    -- Build the open Schubert chart and the tautological frame.
    (chartR, chartS, uVar, chartMatrix, I, f) := openSchubertChartDataGLn(n, lam, mu);
    chartQ := chartR / I;

    -- Extend the chart by the connection coefficients and marked points.
    yVarList := flatten apply(toList(1..N-1), k ->
                    flatten apply(n, i -> apply(n, j -> y_(i,j,k))));
    piBase := getSymbol "pi";
    piVarList := if e <= 1 then {} else
        apply(toList(1..e-1), a -> piBase_a);
    allNewVars := yVarList | piVarList;
    A := if #allNewVars == 0 then chartQ else
             chartQ[allNewVars,
                 Degrees => toList apply(#allNewVars, v -> {0})];
    use A;
    newVarsA := if #allNewVars == 0 then {} else flatten entries vars A;
    piVarsA := if e <= 1 then {} else drop(newVarsA, #yVarList);
    fA := sub(f, A);
    if numrows fA != nN or numcols fA != d then
        error("openNablaSpringer: internal chart-frame size mismatch");

    -- Work over A[u] to test whether nabla preserves the lattice generated by
    -- the columns of chartMatrix.
    SU := A[getSymbol "u"];
    uA := SU_0;
    use SU;

    XA := sub(chartMatrix, SU);
    XAdj := adjugateMatrixGLn(XA);
    XDeriv := diff(uA, XA);

    Ymat := matrix table(n, n, (i,j) -> (
        if N <= 1 then 0_SU else
            sum(toList(1..N-1), k -> sub(y_(i,j,k), SU) * uA^k)
    ));

    diffFactor := if e <= 1 then 1_SU else
        product apply(toList(0..#piVarsA-1), idx -> uA - sub(piVarsA#idx, SU));
    nablaX := Ymat * XA + (diffFactor * uA) * XDeriv;

    -- Since v_u(det X) = sum lam, nabla preserves the lattice iff every entry
    -- of X^* nabla(X) has u-adic valuation at least sum lam.
    testMatrix := XAdj * nablaX;
    relsA := {};
    scan(flatten entries testMatrix, g -> (
        for r from 0 to D - 1 do (
            c := coefficient(uA^r, g);
            if c != 0_A then relsA = append(relsA, c);
        );
    ));

    J := if #relsA == 0 then ideal(0_A) else ideal relsA;

    (J, fA)
);
