-- springerLoci.m2
-- Springer-type loci in the affine Grassmannian for GL_n.
--
-- Requires affGrSchubert.m2 (for schubertGLn, normalizeLambda, etc.)
--
-- FUNCTIONS
--
-- (1) loopFixedSchubertGLn(n, lam)
--     Returns the ideal in (Grass/K) defining the fixed-point subscheme
--     of Gr_lam under loop rotation u |-> t*u.
--
-- (2) constantOrbitIdealGLn(n, lam, mu)
--     Returns the candidate ideal of the constant GL_n-orbit through u^mu
--     by imposing the residue-profile vanishing conditions in Grass/K.
--
-- (2a) constantOrbitAlternativeIdealGLn(n, lam)
--      For n = 3, returns the alternative kernel-flag description of
--      constantOrbitIdealGLn(3, lam, lam) as the scheme-theoretic
--      intersection of the relevant degeneracy loci of the maps
--      w_r : F^3 -> Q, v |-> [u^r v].
--
-- (3) nilpotentOrbitIdealGLn(n, lam, mu)
--     Returns the ideal in (Grass/K)[y_(k,a,b)] generated by {N . p_I}
--     for each Plucker coordinate p_I that appears in the degree-1 part of
--     constantOrbitIdealGLn(n, lam, mu). Here N is a generic nilpotent
--     endomorphism in u * Mat_n(F[u]/u^N).
--
-- (4) nablaOnPluckerGLn(n, lam, I, ii)
--     Returns the direct action of nabla on the Plucker basis vector p_I in
--     /\^D(F[u]^n / u^N), expressed as a linear combination of p_J with
--     coefficients in F[y_(k,a,b), t].
--
-- (5) nablaIdealGLn(n, lam, ii)
--     Returns the ideal in (Grass/K)[y_(k,a,b), t] generated by
--     {nabla . p_I - t^(ii-1) * q * p_I} for each degree-1 basis element
--     p_I of Grass/K, where nabla = N + (u+t)^(ii-1) * u * d/du and
--     q = sum_l binomial(lambda_l, 2). The implementation validates
--     ii >= 1 and caches transition data to avoid repeated rescans.
--
-- (6) openNablaIdealGLn(n, lam, mu, ii)
--     Returns the restriction of nablaIdealGLn(n, lam, ii) to the affine
--     chart around u^mu in the normalized projective model, using the fast
--     open-Schubert equations from affGrSchubert.m2 and the tautological
--     frame returned by openSchubertGLn, then specializing every Plucker
--     coordinate directly on the chart.

load "affGrSchubert.m2"

-------------------------------------------------------------------------------
-- AUXILIARY FUNCTIONS
-------------------------------------------------------------------------------

-- pluckerLoopWeight(N, I)
-- Input:   N - loop length
--          I - Plucker index subset
-- Output:  loop-rotation weight of p_I
pluckerLoopWeight = (N, I) -> sum(I, s -> s % N);

-- basepointLoopWeight(lambda)
-- Input:   lambda - normalized dominant coweight
-- Output:  loop-rotation weight of the distinguished basepoint coordinate
basepointLoopWeight = lambda -> sum(lambda, a -> a * (a - 1) // 2);

-- normalizeMuForProjectiveModel(lam, mu)
-- Inputs:  lam - dominant coweight used for schubertGLn
--          mu  - dominant coweight in the same Schubert variety
-- Output:  mu shifted by the same scalar as lam, so that it is expressed in
--          the normalized projective model used by schubertGLn
normalizeMuForProjectiveModel = (lam, mu) -> (
    shift := lam#(#lam-1);
    apply(mu, a -> a - shift)
);

-- validateProjectiveModelMu(caller, n, lambda, mu)
-- Inputs:  caller - function name for error messages
--          n      - rank of GL_n
--          lambda - normalized dominant coweight used by schubertGLn
--          mu     - coweight written in the same normalized model
-- Output:  validates mu for the residue-profile constructions
validateProjectiveModelMu = (caller, n, lambda, mu) -> (
    if #mu != n then error(caller | ": mu must have length n");
    if not all(0..n-2, i -> mu#i >= mu#(i+1)) then
        error(caller | ": mu must be weakly decreasing");
    if mu#(n-1) < 0 then
        error(caller | ": mu must have nonnegative entries in the normalized model");
    if sum mu != sum lambda then
        error(caller | ": |mu| must equal the size of normalized lambda");
    scan(n-1, k -> (
        if sum take(mu, k+1) > sum take(lambda, k+1) then
            error(caller | ": mu is not <= lambda in dominance order after normalization");
    ));
);

-- pluckerResidueProfile(N, I)
-- Inputs:  N - loop length
--          I - Plucker index subset
-- Output:  list whose r-th entry counts how many elements of I are congruent
--          to r modulo N, i.e. how many chosen rows have u-degree r
pluckerResidueProfile = (N, I) ->
    apply(toList(0..N-1), r -> #select(I, s -> s % N == r));

-- coweightResidueProfile(N, mu)
-- Inputs:  N  - loop length
--          mu - dominant coweight in the normalized projective model
-- Output:  transpose-profile list c_r(mu) = #{i : mu_i > r}; this records
--          how many basis vectors occur in each u-degree slice for u^mu
coweightResidueProfile = (N, mu) ->
    apply(toList(0..N-1), r -> #select(mu, a -> a > r));

-- constantOrbitIdealInQuotientGLn(lambda, muModel, Grass, A)
-- Inputs:  lambda  - normalized dominant coweight
--          muModel - dominant coweight in the normalized projective model
--          Grass   - ambient Plucker ring
--          A       - quotient ring Grass/K
-- Output:  the constant-orbit ideal inside A
constantOrbitIdealInQuotientGLn = (lambda, muModel, Grass, A) -> (
    N := lambda#0;
    D := sum lambda;
    Slist := subsets(#lambda * N, D);
    coordVars := generators Grass;
    muProfile := coweightResidueProfile(N, muModel);

    rels := {};
    for i from 0 to #Slist - 1 do (
        if pluckerResidueProfile(N, Slist#i) != muProfile then (
            g := sub(coordVars#i, A);
            if g != 0_A then rels = append(rels, g);
        );
    );

    if #rels == 0 then ideal(0_A) else trim ideal rels
);

-- sliceRankIdealInQuotientGLn(lambda, slice, rankBound, Grass, A)
-- Inputs:  lambda    - normalized dominant coweight
--          slice     - u-degree r defining w_r : F^n -> Q, v |-> [u^r v]
--          rankBound - desired upper bound on rank(w_r)
--          Grass     - ambient Plucker ring
--          A         - quotient ring Grass/K
-- Output:  ideal in A defining the degeneracy locus rank(w_r) <= rankBound
--
-- In the Plucker model, wedge^(rankBound+1) w_r vanishes exactly when every
-- Plucker coordinate p_I whose index set contains more than rankBound rows of
-- u-degree r vanishes.
sliceRankIdealInQuotientGLn = (lambda, slice, rankBound, Grass, A) -> (
    N := lambda#0;
    D := sum lambda;
    Slist := subsets(#lambda * N, D);
    coordVars := generators Grass;

    if class slice =!= ZZ or slice < 0 or slice >= N then
        error("sliceRankIdealInQuotientGLn: slice must satisfy 0 <= slice < lambda_0");
    if class rankBound =!= ZZ or rankBound < 0 or rankBound > #lambda then
        error("sliceRankIdealInQuotientGLn: rankBound must satisfy 0 <= rankBound <= n");

    rels := {};
    for i from 0 to #Slist - 1 do (
        if (pluckerResidueProfile(N, Slist#i))#slice > rankBound then (
            g := sub(coordVars#i, A);
            if g != 0_A then rels = append(rels, g);
        );
    );

    if #rels == 0 then ideal(0_A) else trim ideal rels
);

-------------------------------------------------------------------------------
-- MAIN FUNCTION 1: loopFixedSchubertGLn
-- Fixed-point subscheme of Gr_{\leq \lambda} under loop rotation.
--
-- Loop rotation acts diagonally on the projective Plucker coordinates. The
-- fixed locus in the ambient projective space is the union of the projective
-- subspaces spanned by coordinates of a single loop weight, so its ideal is
-- generated by pairwise products of coordinates of distinct loop weights.
-- We then pass this ideal to Grass/K.
-------------------------------------------------------------------------------

loopFixedSchubertGLn = (n, lam) -> (
    -- Compute the Schubert ideal
    K := schubertGLn(n, lam);
    Grass := ring K;

    -- Recompute normalized lambda and Plucker index set
    lambda := normalizeLambda(lam);
    N := lambda#0;
    D := sum lambda;
    Slist := subsets(n * N, D);
    -- h homogenizes the affine chart where the basepoint coordinate p_{I_lambda}
    -- is identified with h, so it carries the same loop weight.
    maxWeight := basepointLoopWeight(lambda);
    weights := apply(Slist, I -> pluckerLoopWeight(N, I)) | {maxWeight};
    coordVars := generators Grass;

    -- Work in the projective coordinate ring of the Schubert variety
    A := Grass / K;

    -- Fixed locus = union of weight spaces, cut out by cross-weight products
    rels := {};
    for i from 0 to #coordVars - 1 do (
        xi := sub(coordVars#i, A);
        wi := weights#i;
        for j from i + 1 to #coordVars - 1 do (
            xj := sub(coordVars#j, A);
            wj := weights#j;
            if wi != wj then (
                g := xi * xj;
                if g != 0_A then rels = append(rels, g);
            );
        );
    );

    if #rels == 0 then ideal(0_A) else trim ideal rels
);

-------------------------------------------------------------------------------
-- MAIN FUNCTION 2: constantOrbitIdealGLn
--
--
-- INPUTS
--   n   - rank of GL_n
--   lam - dominant coweight defining the Schubert variety
--   mu  - dominant coweight with mu <= lam and |mu| = |lam|
--
-- OUTPUT
--   An ideal in (Grass/K), where K = schubertGLn(n, lam). 
--   This is the coordinate ring of the constant flag variety embedded into the
--   Schubert vartiety through u^mu. 
-------------------------------------------------------------------------------

constantOrbitIdealGLn = (n, lam, mu) -> (
    -- Validate lambda exactly as in schubertGLn
    if #lam != n then error("constantOrbitIdealGLn: lambda must have length n");
    if not all(0..n-2, i -> lam#i >= lam#(i+1)) then
        error("constantOrbitIdealGLn: lambda must be weakly decreasing");

    -- Move both lambda and mu into the normalized projective model
    lambda := normalizeLambda(lam);
    muModel := normalizeMuForProjectiveModel(lam, mu);
    validateProjectiveModelMu("constantOrbitIdealGLn", n, lambda, muModel);

    -- Compute the Schubert ideal and pass to the quotient ring
    K := schubertGLn(n, lam);
    Grass := ring K;
    A := Grass / K;

    constantOrbitIdealInQuotientGLn(lambda, muModel, Grass, A)
);

-------------------------------------------------------------------------------
-- MAIN FUNCTION 2a: constantOrbitAlternativeIdealGLn
--
-- For n = 3 and lambda = (a,b,0) in the normalized projective model, this
-- returns the scheme-theoretic intersection of the degeneracy loci
--
--   I0: rank(w_0) <= c_0(lambda),
--   I1: rank(w_b) <= 1   when 0 < b < a,
--
-- where w_r : F^3 -> Q is v |-> [u^r v].
--
-- In the ambient projective coordinate ring, V(I0) ∩ V(I1) is defined by the
-- sum I0 + I1.
-------------------------------------------------------------------------------

constantOrbitAlternativeIdealGLn = (n, lam) -> (
    if n != 3 then
        error("constantOrbitAlternativeIdealGLn: currently only implemented for n = 3");
    if #lam != n then
        error("constantOrbitAlternativeIdealGLn: lambda must have length n");
    if not all(0..n-2, i -> lam#i >= lam#(i+1)) then
        error("constantOrbitAlternativeIdealGLn: lambda must be weakly decreasing");

    lambda := normalizeLambda(lam);
    a := lambda#0;
    b := lambda#1;

    K := schubertGLn(n, lam);
    Grass := ring K;
    A := Grass / K;

    lambdaProfile := coweightResidueProfile(a, lambda);
    I0 := sliceRankIdealInQuotientGLn(lambda, 0, lambdaProfile#0, Grass, A);

    if b > 0 and b < a then (
        I1 := sliceRankIdealInQuotientGLn(lambda, b, 1, Grass, A);
        trim(I0 + I1)
    ) else I0
);

-------------------------------------------------------------------------------
-- MAIN FUNCTION 3: nilpotentOrbitIdealGLn
--
-- Computes the ideal generated by {N . p_I} where p_I ranges over the
-- Plucker coordinates that appear in a degree-1 basis of the constant
-- GL_n-orbit ideal through u^mu, and N is a generic nilpotent endomorphism
-- in u * Mat_n(F[u]/u^N).
--
-- The target set is extracted from constantOrbitIdealGLn(n, lam, mu) in the
-- same quotient ring Grass/K, so linear dependencies among Plucker
-- coordinates are taken into account before applying N.
--
-- INPUTS
--   n   - rank of GL_n
--   lam - dominant coweight defining the Schubert variety
--   mu  - dominant coweight with mu <= lam and |mu| = |lam|
--
-- OUTPUT
--   An ideal in (Grass/K)[y_(k,a,b)], where K = schubertGLn(n, lam).
-------------------------------------------------------------------------------

nilpotentOrbitIdealGLn = (n, lam, mu) -> (
    -- Validate
    if #lam != n then error("nilpotentOrbitIdealGLn: lambda must have length n");
    if not all(0..n-2, i -> lam#i >= lam#(i+1)) then
        error("nilpotentOrbitIdealGLn: lambda must be weakly decreasing");

    lambda := normalizeLambda(lam);
    muModel := normalizeMuForProjectiveModel(lam, mu);
    validateProjectiveModelMu("nilpotentOrbitIdealGLn", n, lambda, muModel);

    -- Compute the Schubert ideal
    K := schubertGLn(n, lam);
    Grass := ring K;
    GrassK := Grass / K;

    -- Derived parameters
    N := lambda#0;
    nN := n * N;
    D := sum lambda;
    d := nN - D;
    Slist := subsets(nN, D);
    coordVars := generators Grass;

    -- Degree-1 basis of the constant orbit ideal inside Grass/K. We apply the
    -- nilpotent action to these linear forms directly, mirroring the role of
    -- basis(1, Grass/K) in nilpotentSchubertGLn.
    orbitIdeal := constantOrbitIdealInQuotientGLn(lambda, lambda, Grass, GrassK);
    orbitBasisForms := flatten entries gens image basis(1, orbitIdeal);

    -- Build GrassKX = (Grass/K)[y_(k,a,b)]
    yVarList := flatten apply(toList(1..N-1), k ->
                    flatten apply(n, a -> apply(n, b -> y_(k,a,b))));
    GrassKX := if #yVarList == 0 then GrassK else
                   GrassK[yVarList,
                       Degrees => toList apply(#yVarList, v -> {0})];
    use GrassKX;

    -- Record the Plucker-coordinate coefficients of each degree-1 basis vector.
    -- The homogenizing coordinate h contributes no nilpotent term, so it is
    -- omitted here and yields the zero generator when a basis vector is h.
    orbitBasisData := apply(orbitBasisForms, g -> (
        gLift := lift(g, Grass);
        select(apply(toList(0..#Slist-1), i -> (
            c := coefficient(coordVars#i, gLift);
            if c != 0_Grass then (i, sub(c, GrassKX)) else null
        )), pair -> pair =!= null)
    ));

    -- Build a lookup table: subset (as sequence) -> index in Slist
    subsetIndex := hashTable apply(#Slist, i -> (toSequence Slist#i, i));

    -- nOnBasis(s): nilpotent action on basis vector s = b*N + r
    nOnBasis := s -> (
        b := s // N; r := s % N;
        flatten apply(toList(1..N-1), k ->
            if r + k < N then apply(n, a -> (y_(k,a,b), a*N + r + k))
            else {})
    );

    -- insertSign: sign from swapping element t into sorted list S at position k
    insertSign := (S, k, t) -> (
        nLeft  := #select(toList(0..k-1),    j -> S#j > t);
        nRight := #select(toList(k+1..#S-1), j -> S#j < t);
        (-1)^(nLeft + nRight)
    );

    -- Build action triples for ALL sources, recording (source, target, coeff).
    actionTriples := {};
    scan(#Slist, srcIdx -> (
        S := Slist#srcIdx;
        Sc := sort(select(toList(0..nN-1), j -> not member(j, set S)));
        for k from 0 to d-1 do (
            for pair in nOnBasis(Sc#k) do (
                t := pair#1;
                if not member(t, set Sc) then (
                    newSc := sort(drop(Sc, {k,k}) | {t});
                    Sprime := sort(select(toList(0..nN-1),
                                          j -> not member(j, set newSc)));
                    sgn := insertSign(Sc, k, t);
                    tgtIdx := subsetIndex#(toSequence Sprime);
                    actionTriples = append(actionTriples,
                        (srcIdx, tgtIdx, sgn * pair#0));
                )
            )
        )
    ));

    -- Precompute N^T . p_{S'} for every target subset S'.
    targetActions := apply(toList(0..#Slist-1), tgtIdx -> (
        result := 0_GrassKX;
        scan(actionTriples, trip -> (
            if trip#1 == tgtIdx then
                result = result + trip#2 * p_(toSequence(Slist#(trip#0)));
        ));
        result
    ));

    -- Apply N^T to each degree-1 basis element of the constant orbit ideal.
    genList := apply(orbitBasisData, coeffData -> (
        result := 0_GrassKX;
        scan(coeffData, pair -> (
            result = result + pair#1 * targetActions#(pair#0);
        ));
        result
    ));

    if #genList == 0 then ideal(0_GrassKX) else ideal genList
);

-------------------------------------------------------------------------------
-- MAIN FUNCTION 4: nablaOnPluckerGLn
--
-- Computes nabla . p_I directly in /\^D(F[u]^n / u^N), where p_I is
-- interpreted as the wedge basis vector indexed by the D-subset I.
--
-- INPUTS
--   n   - rank of GL_n
--   lam - dominant coweight defining the Schubert variety
--   I   - D-subset of {0, ..., nN-1}, where D = |lambda| and N = lambda_0
--   ii  - positive integer parameter
--
-- OUTPUT
--   An element of a polynomial ring F[p_J, y_(k,a,b), t] containing exactly
--   the Plucker symbols p_J that appear in nabla . p_I.
-------------------------------------------------------------------------------

nablaOnPluckerGLn = (n, lam, I, ii) -> (
    -- Validate
    if #lam != n then error("nablaOnPluckerGLn: lambda must have length n");
    if not all(0..n-2, i -> lam#i >= lam#(i+1)) then
        error("nablaOnPluckerGLn: lambda must be weakly decreasing");
    if class ii =!= ZZ or ii < 1 then
        error("nablaOnPluckerGLn: ii must be a positive integer");

    lambda := normalizeLambda(lam);

    -- Derived parameters
    N := lambda#0;
    nN := n * N;
    D := sum lambda;

    if class I =!= List and class I =!= Set then
        error("nablaOnPluckerGLn: I must be a list or set");

    Ilist := sort(if class I === Set then toList I else I);
    if #Ilist != D then
        error("nablaOnPluckerGLn: I must have cardinality D = " | toString D);
    if #set Ilist != D then
        error("nablaOnPluckerGLn: I must not contain repeated indices");
    if not all(Ilist, s -> class s === ZZ and 0 <= s and s < nN) then
        error("nablaOnPluckerGLn: entries of I must lie in {0, ..., " | toString(nN-1) | "}");

    Iset := set Ilist;

    -- insertSign: sign from swapping element tgt into sorted list I at position k
    insertSign := (S, k, tgt) -> (
        nLeft  := #select(toList(0..k-1),    j -> S#j > tgt);
        nRight := #select(toList(k+1..#S-1), j -> S#j < tgt);
        (-1)^(nLeft + nRight)
    );

    -- First collect the Plucker symbols that can appear in nabla . p_I.
    targetSubsets := {Ilist};
    addTargetSubset := J -> (
        key := toSequence J;
        if not member(key, apply(targetSubsets, K -> toSequence K)) then
            targetSubsets = append(targetSubsets, J);
    );

    maxDiffShift := if ii-1 < N-1 then ii-1 else N-1;
    for k from 0 to D-1 do (
        s := Ilist#k;
        b := s // N;
        r := s % N;
        maxShift := N - r - 1;

        if maxShift > 0 then (
            scan(toList(1..maxShift), kk -> (
                scan(toList(0..n-1), a -> (
                    tgt := a*N + r + kk;
                    if not member(tgt, Iset) then
                        addTargetSubset(sort toList((Iset - set {s}) + set {tgt}));
                ))
            ));

            diffBound := if maxShift < maxDiffShift then maxShift else maxDiffShift;
            if r > 0 and diffBound > 0 then (
                scan(toList(1..diffBound), m -> (
                    tgt := b*N + r + m;
                    if not member(tgt, Iset) then
                        addTargetSubset(sort toList((Iset - set {s}) + set {tgt}));
                ))
            );
        );
    );

    -- Build the polynomial ring containing the Plucker symbols that appear,
    -- together with the y_(k,a,b) and t coefficients of nabla.
    pVarList := apply(targetSubsets, J -> p_(toSequence J));
    yVarList := flatten apply(toList(1..N-1), kk ->
                    flatten apply(n, a -> apply(n, b -> y_(kk,a,b))));
    varList := pVarList | yVarList | {symbol t};
    R := if #varList == 0 then F[] else F[varList];
    use R;

    ringVars := generators R;
    pRingVars := take(ringVars, #targetSubsets);
    subsetVar := hashTable apply(#targetSubsets, i ->
        (toSequence(targetSubsets#i), pRingVars#i));

    tPower := t^(ii-1);
    expr := sub(pluckerLoopWeight(N, Ilist), R) * tPower
            * subsetVar#(toSequence Ilist);

    -- Add the off-diagonal contributions coming from N and the positive u-shifts
    -- in (u+t)^(ii-1) * u * d/du.
    for k from 0 to D-1 do (
        s := Ilist#k;
        b := s // N;
        r := s % N;
        maxShift := N - r - 1;

        if maxShift > 0 then (
            scan(toList(1..maxShift), kk -> (
                scan(toList(0..n-1), a -> (
                    tgt := a*N + r + kk;
                    if not member(tgt, Iset) then (
                        J := sort toList((Iset - set {s}) + set {tgt});
                        expr = expr + insertSign(Ilist, k, tgt) * y_(kk,a,b)
                                      * subsetVar#(toSequence J);
                    )
                ))
            ));

            diffBound := if maxShift < maxDiffShift then maxShift else maxDiffShift;
            if r > 0 and diffBound > 0 then (
                scan(toList(1..diffBound), m -> (
                    tgt := b*N + r + m;
                    if not member(tgt, Iset) then (
                        J := sort toList((Iset - set {s}) + set {tgt});
                        coeff := sub(r * binomial(ii-1, m), R) * t^(ii-1-m);
                        expr = expr + insertSign(Ilist, k, tgt) * coeff
                                      * subsetVar#(toSequence J);
                    )
                ))
            );
        );
    );

    expr
);

-------------------------------------------------------------------------------
-- MAIN FUNCTION 5: nablaIdealGLn
--
-- Computes the ideal generated by {nabla . p_I - t^(ii-1) * q * p_I} where
-- p_I ranges over the degree-1 basis of Grass/K, and
--   nabla = N + (u+t)^(ii-1) * u * d/du
-- with N a generic nilpotent endomorphism in u * Mat_n(F[u]/u^N).
--
-- INPUTS
--   n   - rank of GL_n
--   lam - dominant coweight defining the Schubert variety
--   ii  - positive integer parameter
--
-- OUTPUT
--   An ideal in (Grass/K)[y_(k,a,b), t], where K = schubertGLn(n, lam).
--   The transition data is cached once per Plucker subset.
-------------------------------------------------------------------------------

nablaIdealGLn = (n, lam, ii) -> (
    -- Validate
    if #lam != n then error("nablaIdealGLn: lambda must have length n");
    if not all(0..n-2, i -> lam#i >= lam#(i+1)) then
        error("nablaIdealGLn: lambda must be weakly decreasing");
    if class ii =!= ZZ or ii < 1 then
        error("nablaIdealGLn: ii must be a positive integer");

    lambda := normalizeLambda(lam);

    -- Compute the Schubert ideal
    K := schubertGLn(n, lam);
    Grass := ring K;
    GrassK := Grass / K;

    -- Derived parameters
    N := lambda#0;
    nN := n * N;
    D := sum lambda;
    d := nN - D;
    Slist := subsets(nN, D);
    allIndices := toList(0..nN-1);

    -- Scalar q = sum_l binomial(lambda_l, 2)
    q := sum(lambda, l -> binomial(l, 2));

    -- Build GrassKX = (Grass/K)[y_(k,a,b), t]
    yVarList := flatten apply(toList(1..N-1), k ->
                    flatten apply(n, a -> apply(n, b -> y_(k,a,b))));
    allNewVars := yVarList | {symbol t};
    GrassKX := if #allNewVars == 0 then GrassK else
                   GrassK[allNewVars,
                       Degrees => toList apply(#allNewVars, v -> {0})];
    use GrassKX;

    tPower := t^(ii-1);

    -- Identify the basepoint Plucker coordinate corresponding to h.
    basepointSubset := sort flatten apply(n, j ->
                           apply(lambda#j, r -> j*N + r));
    subsetIndex := hashTable apply(#Slist, i -> (toSequence Slist#i, i));
    hIdx := subsetIndex#(toSequence basepointSubset);
    pluckerVars := apply(Slist, S -> p_(toSequence S));

    -- Degree-1 basis of GrassK, decomposed sparsely into Plucker coefficients.
    basisForms := flatten entries basis(1, GrassK);
    basisData := apply(basisForms, g -> (
        gLift := lift(g, Grass);
        coeffData := coefficients gLift;
        mons := flatten entries coeffData#0;
        coeffs := flatten entries coeffData#1;
        select(apply(#mons, j -> (
            idx := index(mons#j);
            coeff := sub(coeffs#j, GrassKX);
            if idx < #Slist then (idx, coeff)
            else if idx == #Slist then (hIdx, coeff)
            else null
        )), pair -> pair =!= null)
    ));

    -- Cache complement data for each subset once.
    sourceSets := apply(Slist, S -> set S);
    sourceComplements := apply(#Slist, srcIdx ->
        select(allIndices, j -> not member(j, sourceSets#srcIdx)));
    sourceComplementSets := apply(sourceComplements, Sc -> set Sc);
    sourcePluckerWeights := apply(Slist, S -> sum(S, s -> s % N));

    -- nablaOnBasisData#s stores the off-diagonal action on basis vector s.
    maxDiffShift := if ii-1 < N-1 then ii-1 else N-1;
    diffBaseScalars := if maxDiffShift <= 0 then {} else
        apply(toList(1..maxDiffShift), m ->
            sub(binomial(ii-1, m), GrassKX) * t^(ii-1-m));
    nablaOnBasisData := apply(allIndices, s -> (
        b := s // N;
        r := s % N;
        maxShift := N - r - 1;
        nTerms := if maxShift <= 0 then {} else
            flatten apply(toList(1..maxShift), k ->
                apply(n, a -> (y_(k,a,b), a*N + r + k)));
        diffBound := if maxShift < maxDiffShift then maxShift else maxDiffShift;
        diffTerms := if r == 0 or diffBound <= 0 then {} else
            apply(toList(1..diffBound), m ->
                (sub(r, GrassKX) * diffBaseScalars#(m-1), b*N + r + m));
        nTerms | diffTerms
    ));

    -- insertSign: sign from swapping element tgt into sorted list S at position k
    insertSign := (S, k, tgt) -> (
        nLeft  := #select(toList(0..k-1),    j -> S#j > tgt);
        nRight := #select(toList(k+1..#S-1), j -> S#j < tgt);
        (-1)^(nLeft + nRight)
    );

    -- Accumulate off-diagonal nabla action directly by target subset.
    targetActions = new MutableList from apply(#Slist, i -> 0_GrassKX);
    scan(#Slist, srcIdx -> (
        S := Slist#srcIdx;
        Sset := sourceSets#srcIdx;
        Sc := sourceComplements#srcIdx;
        ScSet := sourceComplementSets#srcIdx;
        pS := pluckerVars#srcIdx;
        for k from 0 to d-1 do (
            s := Sc#k;
            for pair in nablaOnBasisData#s do (
                tgt := pair#1;
                if not member(tgt, ScSet) then (
                    Sprime := sort toList((Sset - set {tgt}) + set {s});
                    sgn := insertSign(Sc, k, tgt);
                    tgtIdx := subsetIndex#(toSequence Sprime);
                    targetActions#tgtIdx = targetActions#tgtIdx + sgn * pair#0 * pS;
                )
            )
        )
    ));

    -- Assemble generators: nabla . f - t^(ii-1) * q * f for each basis element f.
    genList := apply(basisData, coeffData -> (
        offDiag := 0_GrassKX;
        diagCorr := 0_GrassKX;
        scan(coeffData, pair -> (
            srcIdx := pair#0;
            coeff := pair#1;
            pS := pluckerVars#srcIdx;
            offDiag = offDiag + coeff * targetActions#srcIdx;
            diagCorr = diagCorr + coeff * sub(sourcePluckerWeights#srcIdx - q, GrassKX)
                           * tPower * pS;
        ));
        offDiag + diagCorr
    ));

    if #genList == 0 then ideal(0_GrassKX) else ideal genList
);

-------------------------------------------------------------------------------
-- MAIN FUNCTION 6: openNablaIdealGLn
--
-- Computes the restriction of nablaIdealGLn(n, lam, ii) to the affine chart
-- around u^mu, but avoids the global Plucker presentation. Instead it works in
-- the quotient A = R / I, where (R, S, uVar, E, I, Q) =
-- openSchubertChartDataGLn(n, lambda, muModel) and Q is the chart frame of the
-- tautological bundle in F[u]^n / u^N.
-- Here lambda and muModel are the normalized projective-model coweights.
--
-- INPUTS
--   n   - rank of GL_n
--   lam - dominant coweight defining the Schubert variety
--   mu  - dominant coweight with mu <= lam and |mu| = |lam|
--   ii  - positive integer parameter
--
-- OUTPUT
--   An ideal in A[y_(k,a,b), t], where A is the coordinate ring of the affine
--   open chart around u^mu in the normalized projective model.
-------------------------------------------------------------------------------

openNablaIdealGLn = (n, lam, mu, ii) -> (
    -- Validate
    if #lam != n then error("openNablaIdealGLn: lambda must have length n");
    if not all(0..n-2, i -> lam#i >= lam#(i+1)) then
        error("openNablaIdealGLn: lambda must be weakly decreasing");
    if class ii =!= ZZ or ii < 1 then
        error("openNablaIdealGLn: ii must be a positive integer");

    lambda := normalizeLambda(lam);
    muModel := normalizeMuForProjectiveModel(lam, mu);
    validateProjectiveModelMu("openNablaIdealGLn", n, lambda, muModel);

    -- Derived parameters in the normalized projective model
    N := lambda#0;
    nN := n * N;
    D := sum lambda;
    d := nN - D;
    if d <= 0 or d >= nN then
        error("openNablaIdealGLn: degenerate case, d = " | toString d);

    Slist := subsets(nN, D);
    allIndices := toList(0..nN-1);
    subsetIndex := hashTable apply(#Slist, i -> (toSequence Slist#i, i));

    -- Scalar q = sum_l binomial(lambda_l, 2)
    q := sum(lambda, l -> binomial(l, 2));

    -- Build the fast affine chart and reuse the tautological frame returned
    -- by openSchubertChartDataGLn instead of reconstructing it here.
    (chartR, chartS, uVar, chartMatrix, chartIdeal, chartFrame) := openSchubertChartDataGLn(n, lambda, muModel);
    A := chartR / chartIdeal;

    -- Extend by the generic nilpotent coefficients and the parameter t
    yVarList := flatten apply(toList(1..N-1), k ->
                    flatten apply(n, a -> apply(n, b -> y_(k,a,b))));
    allNewVars := yVarList | {symbol t};
    AX := if #allNewVars == 0 then A else
              A[allNewVars,
                  Degrees => toList apply(#allNewVars, v -> {0})];
    use AX;

    tPower := t^(ii-1);

    Q := sub(chartFrame, AX);
    if numrows Q != nN or numcols Q != d then
        error("openNablaIdealGLn: internal chart-frame size mismatch");

    -- Specialize every Plucker coordinate on the chart via complementary minors.
    sourceSets := apply(Slist, S -> set S);
    sourceComplements := apply(#Slist, srcIdx ->
        select(allIndices, j -> not member(j, sourceSets#srcIdx)));
    sourceComplementSets := apply(sourceComplements, Sc -> set Sc);
    sourcePluckerWeights := apply(Slist, S -> sum(S, s -> s % N));
    activeSourceIdx := select(toList(0..#Slist-1), i -> sourcePluckerWeights#i <= q);
    activeTargetIdx := select(toList(0..#Slist-1), i -> sourcePluckerWeights#i < q);
    colIndices := toList(0..d-1);
    pluckerImages := apply(#Slist, i ->
        if sourcePluckerWeights#i <= q then
            det submatrix(Q, sourceComplements#i, colIndices)
        else 0_AX);

    -- nablaOnBasisData#s stores the off-diagonal action on basis vector s.
    maxDiffShift := if ii-1 < N-1 then ii-1 else N-1;
    diffBaseScalars := if maxDiffShift <= 0 then {} else
        apply(toList(1..maxDiffShift), m ->
            sub(binomial(ii-1, m), AX) * t^(ii-1-m));
    nablaOnBasisData := apply(allIndices, s -> (
        b := s // N;
        r := s % N;
        maxShift := N - r - 1;
        nTerms := if maxShift <= 0 then {} else
            flatten apply(toList(1..maxShift), k ->
                apply(n, a -> (y_(k,a,b), a*N + r + k)));
        diffBound := if maxShift < maxDiffShift then maxShift else maxDiffShift;
        diffTerms := if r == 0 or diffBound <= 0 then {} else
            apply(toList(1..diffBound), m ->
                (sub(r, AX) * diffBaseScalars#(m-1), b*N + r + m));
        nTerms | diffTerms
    ));

    -- insertSign: sign from swapping element tgt into sorted list S at position k
    insertSign := (S, k, tgt) -> (
        nLeft  := #select(toList(0..k-1),    j -> S#j > tgt);
        nRight := #select(toList(k+1..#S-1), j -> S#j < tgt);
        (-1)^(nLeft + nRight)
    );

    -- Accumulate off-diagonal nabla action directly by target subset.
    targetActions = new MutableList from apply(#Slist, i -> 0_AX);
    scan(activeSourceIdx, srcIdx -> (
        S := Slist#srcIdx;
        Sset := sourceSets#srcIdx;
        Sc := sourceComplements#srcIdx;
        ScSet := sourceComplementSets#srcIdx;
        pS := pluckerImages#srcIdx;
        for k from 0 to d-1 do (
            s := Sc#k;
            for pair in nablaOnBasisData#s do (
                tgt := pair#1;
                if not member(tgt, ScSet) then (
                    Sprime := sort toList((Sset - set {tgt}) + set {s});
                    sgn := insertSign(Sc, k, tgt);
                    tgtIdx := subsetIndex#(toSequence Sprime);
                    targetActions#tgtIdx = targetActions#tgtIdx + sgn * pair#0 * pS;
                )
            )
        )
    ));

    -- Coordinates of weight q already satisfy nabla.p_I = t^(ii-1) * q * p_I.
    genList := apply(activeTargetIdx, srcIdx ->
        targetActions#srcIdx
        + sub(sourcePluckerWeights#srcIdx - q, AX) * tPower * pluckerImages#srcIdx
    );

    if #genList == 0 then ideal(0_AX) else ideal genList
);

-------------------------------------------------------------------------------
-- COMPATIBILITY ALIAS
-------------------------------------------------------------------------------

nablaIdealGLnFast = nablaIdealGLn;
